/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dictionaryapplication;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 * add word frame
 * @author HH
 */
public class addWordJFrame extends javax.swing.JFrame {

    /**
     * Creates new form addWordJFrame
     */
    public addWordJFrame() {
        initComponents();
        errorJLabel1.setText(" ");
        errorJLabel2.setText(" ");
        errorJLabel3.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newWordJTextField = new javax.swing.JTextField();
        errorJLabel = new javax.swing.JLabel();
        addJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        xerrorJLabel = new javax.swing.JLabel();
        errorJLabel1 = new javax.swing.JLabel();
        errorJLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        explainJTextArea = new javax.swing.JTextArea();
        errorJLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm từ mới");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setResizable(false);

        newWordJTextField.setForeground(new java.awt.Color(153, 153, 153));
        newWordJTextField.setText(" Nhập từ mới");
        newWordJTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newWordJTextFieldMouseClicked(evt);
            }
        });

        errorJLabel.setForeground(new java.awt.Color(0, 0, 153));

        addJButton.setText("Thêm từ");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Từ mới:");

        xerrorJLabel.setForeground(new java.awt.Color(204, 0, 0));

        errorJLabel1.setForeground(new java.awt.Color(204, 0, 0));
        errorJLabel1.setText("Từ đã tồn tại");

        errorJLabel3.setForeground(new java.awt.Color(0, 153, 51));
        errorJLabel3.setText("jLabel1");

        jLabel1.setText("Giải thích từ:");

        explainJTextArea.setColumns(20);
        explainJTextArea.setRows(5);
        jScrollPane1.setViewportView(explainJTextArea);

        errorJLabel2.setForeground(new java.awt.Color(204, 0, 0));
        errorJLabel2.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorJLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(errorJLabel1)
                                .addComponent(newWordJTextField)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(addJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(errorJLabel3)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newWordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorJLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorJLabel2)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJButton)
                    .addComponent(errorJLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newWordJTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newWordJTextFieldMouseClicked
        // TODO add your handling code here:
        if (newWordJTextField.getText().equals(" Nhập từ mới")) {
            newWordJTextField.setText(null);
            newWordJTextField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_newWordJTextFieldMouseClicked

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        String newWord = newWordJTextField.getText();
        String explain = explainJTextArea.getText();
        boolean check = false;
        if (newWord.equals(" Nhập từ mới") || newWord.equals("")) {
            errorJLabel1.setText("Vui lòng nhập từ mới!");
        } else {
            // is exist ?
            if (Data.SetOfWordTarget.contains(newWord)) {
                errorJLabel1.setText("Từ đã tồn tại!");
                errorJLabel3.setText(" ");
            } else {
                check = true;
                errorJLabel1.setText(" ");
            }
        }
        
        if (explain == null || explain.equals("")) {
            errorJLabel2.setText("Vui lòng nhập phần giải thích từ!");
            check = false;
            errorJLabel3.setText(" ");
        }
        
        if(check == true) {
            errorJLabel2.setText(" ");
            errorJLabel3.setText(" ");
            Data.ListOfWords.put(newWord, explain.replace('\n', '|'));
            DictionaryApplication.setListModel();
            try {
                // export to file
                Data.addNewWordToFile(newWord, explain);
            } catch (IOException ex) {
                Logger.getLogger(addWordJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            errorJLabel3.setText("Thêm từ thành công!");
        } 
    }//GEN-LAST:event_addJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JLabel errorJLabel;
    private javax.swing.JLabel errorJLabel1;
    private javax.swing.JLabel errorJLabel2;
    private javax.swing.JLabel errorJLabel3;
    private javax.swing.JTextArea explainJTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField newWordJTextField;
    private javax.swing.JLabel xerrorJLabel;
    // End of variables declaration//GEN-END:variables
}
