/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dictionaryapplication;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author HH
 */
public class fixWordJFrame extends javax.swing.JFrame {
    /**
     * Creates new form fixWordJFrame
     */
    public fixWordJFrame() {
        initComponents(); 
        errorJLabel1.setText(" ");
        errorJLabel2.setText(" ");     
        errorJLabel3.setText(" ");
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        notice = new javax.swing.JOptionPane();
        fixWordJTextField = new javax.swing.JTextField();
        errorJLabel2 = new javax.swing.JLabel();
        fixJButton = new javax.swing.JButton();
        errorJLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        errorJLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fixExplainJTextArea = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        jLabel7.setText("jLabel7");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sửa từ");
        setBackground(new java.awt.Color(255, 255, 255));

        fixWordJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixWordJTextFieldActionPerformed(evt);
            }
        });

        errorJLabel2.setForeground(new java.awt.Color(204, 0, 0));
        errorJLabel2.setText("jLabel3");

        fixJButton.setText("Sửa từ");
        fixJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixJButtonActionPerformed(evt);
            }
        });

        errorJLabel1.setForeground(new java.awt.Color(204, 0, 0));
        errorJLabel1.setText("Từ đã tồn tại");

        jLabel8.setText("Từ mới:");

        errorJLabel3.setForeground(new java.awt.Color(0, 153, 51));
        errorJLabel3.setText("jLabel1");

        jLabel9.setText("Giải thích từ:");

        fixExplainJTextArea.setColumns(20);
        fixExplainJTextArea.setRows(5);
        jScrollPane1.setViewportView(fixExplainJTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorJLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(errorJLabel1)
                                .addComponent(fixWordJTextField)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(fixJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(errorJLabel3)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fixWordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorJLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorJLabel2)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fixJButton)
                    .addComponent(errorJLabel3))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void fixJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixJButtonActionPerformed
        // TODO add your handling code here:
        String fixWord = fixWordJTextField.getText();
        String fixExplain = fixExplainJTextArea.getText();
        if (fixExplain == null || fixExplain.equals("")) {
            errorJLabel2.setText("Vui lòng nhập phần giải thích từ!");
        } else if(checkFixWord(fixWord) == false) {
            
        } else {
            errorJLabel1.setText(" ");
            errorJLabel2.setText(" ");
            Data.ListOfWords.remove(fixWord);
            Data.ListOfWords.put(fixWord, fixExplain);
            DictionaryApplication.setListModel();
            try {
                Data.addNewWordToFile(fixWord, fixExplain);
            } catch (IOException ex) {
                Logger.getLogger(fixWordJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            errorJLabel3.setText("Sửa từ thành công!");
        }
    }//GEN-LAST:event_fixJButtonActionPerformed

    private void fixWordJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixWordJTextFieldActionPerformed
        // TODO add your handling code here:
        String fixWord = fixWordJTextField.getText();
        if (checkFixWord(fixWord) == true) {
            fixExplainJTextArea.setText(Data.ListOfWords.get(fixWord).replace('|', '\n'));
        }
    }//GEN-LAST:event_fixWordJTextFieldActionPerformed

    private boolean checkFixWord(String fixWord) {
        boolean check = false;
        if (fixWord.equals(" Nhập từ muốn sửa") || fixWord.equals("")) {
            errorJLabel1.setText("Vui lòng nhập từ muốn sửa!");
        } else {
            if (!Data.SetOfWordTarget.contains(fixWord)) {
                errorJLabel1.setText("Từ không tồn tại!");
            } else {
                check = true;
                errorJLabel1.setText(" ");
            }
        }
        return check;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorJLabel1;
    private javax.swing.JLabel errorJLabel2;
    private javax.swing.JLabel errorJLabel3;
    private javax.swing.JTextArea fixExplainJTextArea;
    private javax.swing.JButton fixJButton;
    private javax.swing.JTextField fixWordJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JOptionPane notice;
    // End of variables declaration//GEN-END:variables
}
